services:
  main-api:
    build:
      context: .
      args:
        MODE: ${MODE:-release}
    environment:
      # `DATABASE_URL` uses the internal port to connect to `main_db` (the container one)
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:meetUN@main_db:5432/meetun?sslmode=disable}
      PORT: 8008
    depends_on:
      - main-db
    ports:
      - 8008:8008

  main-db:
    image: postgres:17-alpine
    hostname: main_db # Hostname for which the container will be reachable
    # The port exposed within the hostname is `5432` unless modified
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-meetUN}
      POSTGRES_DB: ${POSTGRES_DB:-meetun}
    volumes:
      - main-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
